### ISSUE TITLE
Multi displayで２つ以上表示している場合、ドットもその数に合わせて表示できないか

### ISSUE THREAD

**Issue by ghost** [inc2734/spider#12]
Multi displayで横２つ出ている際は、
矢印を押した際にドットが最後に移動した後に最後ページの1ページ前に再度戻ります。
また最後のドットが点灯されないので、最後のページに移動できない感じがあるので、ドットも画面の表示数に合わせて表示させておくなどはどうです？

**Comment by inc2734** [comment]
要は最後のドットを消したいわけですよね？これやりたくはあるんですけど、表示数の設定を持っているわけではなくて CSS 設定できるようにしている都合上、無理なんじゃない…？って感じになってそのままにしています。うまいこと計算する方法があれば良いのですが…。

**Comment by ghost** [comment]
あ、なるほど…。

最後のドットを消すと言うか、○○○●○となっていて２つ出ているのなら○○○●●にするのも有りかもって考えてます。
（現在の画面で２つ出ていたらドットも２つ単位で考える…のはどうかなと）
●●○○○から１回移動で○●●○○と。こう言う表示をすると２つじゃなくて１つだけ移動したって解りやすいんです。
現状、これができるスライドコンポーネント（ライブラリ？）って良いのが無いので、こう言うのもオプションなりで可能になれば良いなーとか思ってます。
海外製のモバイルアプリケーションでは、この表示を行うライブラリがあるんですが…。
（ドットは１つって考えの方が強いからか…あまり浸透してないですが）

CSSだとnext（次要素）とかを使って上手くactiveからの何個目を…って感じでできないかなーとかゴニョゴニョ考えてみてはいるんですが、最後のドットを消す…って方式になるとより難しいですね…。

---

余計なものが無いのもあってReact Appでもサクッと使いやすいですね、これ。

**Comment by inc2734** [comment]
あー二個つけるですか。できればやりたいですねー。現状 `.spider__canvas` の `data-current` を参照しているだけなので、枠内に入っているものみたいな判定に変えれれば良さそうですけども…。
