### ISSUE TITLE
Android Chrome で arrow / dot をクリックしても dot が current にならない

### ISSUE THREAD

**Issue by inc2734** [inc2734/spider#5]

**Comment by ghost** [comment]
iOS Safariでも起きる場合有り。（一応報告）

**Comment by inc2734** [comment]
https://github.com/inc2734/spider/blob/master/src/js/canvas.js#L9-L20
のコードがスマホだと意図したとおりに動いてないみたいなんですよね。`data-current` が更新されるようになれば解決するはず。
