### ISSUE TITLE
Android Chrome で Arrows が1スライドしか反応しない

### ISSUE THREAD

**Issue by inc2734** [inc2734/spider#6]

**Comment by ghost** [comment]
表題の件、iOSのSafariでも起こるようです。

また、アローを押した後、たまにフリック操作がカクつくか反応しなくなる場合があるようです。
シミュレータではあまり起こらないっぽい。iPadだと起こりにくい。
（メモリの問題かとも思ったが、シミュレータのメモリ低下状態をシミュレートしても再現せず

**Comment by inc2734** [comment]
#5 が解決すれば解決するので close
